config/routes.rb
PartyManager::Application.routes.draw do

    
    get "users/new"
  
    match '/signup',  :to => 'users#new'
    match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/baby',   :to => 'pages#baby'
    match '/graduation',   :to => 'pages#graduation'
    match '/generic',   :to => 'pages#generic'
    match '/birthday',   :to => 'pages#birthday'
    root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  
  def baby
    @title = "Baby Shower"
  end
  
  def graduation
    @title = "Graduation Party"
  end
  
  def generic
    @title = "Party Time"
  end
  
  def birthday
    @title = "Birthday Party"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @title = "Sign up"
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "The Party Manager System"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'partials/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'partials/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'partials/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  Done by Shamma Ahmed Al Hetmi.
</p>

app/views/pages/baby.html.erb
<h1>Baby Shower</h1>
<p>
  This is the About page for the Party Manager System
</p>

app/views/pages/birthday.html.erb
<h1>Birthday Party</h1>
<p>
  This is the About page for the Party Manager System
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Email: shetmi@qatar.cmu.edu
</p>

app/views/pages/generic.html.erb
<h1>Party Time</h1>
<p>
  This is the About page for the Party Manager System
</p>

app/views/pages/graduation.html.erb
<h1>Graduation Party</h1>
<p>
  This is the About page for the Party Manager System
</p>

app/views/pages/home.html.erb
    <h1>Welcome to the Party Manager System!</h1>
    <p>
      Need help creating a cool party invitation? Well worry no more, we offer four great designs that you can use for any occasion. Just click on which type of party you're having and voila! you'll get the most perfect party invitation you have ever seen.
    </p>

	<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/partials/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/partials/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Party Manager", :class => "round") %>
<%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/partials/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>